### ISSUE TITLE
unsupported operand type(s) for +=: 'dict' and 'dict'

### ISSUE THREAD

**Issue by liZe** [cenk/github-flask#32]
The [Search API](https://developer.github.com/v3/search/) provides a multi-page search, but returns dicts (and not lists), leading to an error. That's the only multi-page dict I've found in the API.

A quick fix would be to use something like that in `request`:

```python
body = response.json()
if isinstance(body, list):
    result += body
elif isinstance(body, dict) and 'items' in body:
    result['items'] += body['items']
```

Any better ideas?

**Comment by cenkalti** [comment]
LGTM. I would merge it if you make a PR.

**Comment by liZe** [comment]
@cenk Done!

**Comment by cenk** [comment]
Thank you. I have updated the version on PyPI: https://pypi.python.org/pypi/GitHub-Flask/3.1.2
