### ISSUE TITLE
data is not supported in PUT method?

### ISSUE THREAD

**Issue by cangelzz** [cenk/github-flask#34]
In Github API, I want to update a file https://developer.github.com/v3/repos/contents/#update-a-file
however I see the source code it does not support data parameter in the PUT method, even not in the request method.  I want the PUT method has the signature of POST so it can sends data to Github. Is it a particular design or is it missed?

**Comment by cenk** [comment]
The parameter was missed. I added it and uploaded a new version of the library to PyPI as 3.1.3.

I hope that I don't broke anything with this commit.

Please reopen the issue if it does not work.

**Comment by cangelzz** [comment]
thanks, it works
